// Copyright AB. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Combat)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Combat_Attack)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Combat_Attack_Unarmed)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Combat_Attack_Unarmed_Cross)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Combat_Attack_Unarmed_Jab)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Combat_Attack_Unarmed_LeadHook)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Combat_Attack_Unarmed_RearUppercut)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Combat_Attack_Unarmed_RearUppercutPower)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Combat_Defense)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Combat_Defense_Unarmed)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Combat_Defense_Unarmed_Block)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Primary_Creativity)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Primary_Dexterity)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Primary_Intelligence)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Primary_Resilience)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Primary_Speed)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Primary_Strength)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Vital_Health)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Vital_MaxHealth)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Effect_HitReaction)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Animation_CancelWindow_Begin)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Animation_CancelWindow_End)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Animation_HitBox_Activate)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Animation_HitBox_Deactivate)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Consumable_Apple)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Weapon_Sword)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Npc_Balthazar)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Npc_Carver)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Npc_Darrow)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_FasterWalk)
