// Copyright AB. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Tutorial)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Tutorial_HowToLook)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Tutorial_HowToJump)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Tutorial_HowToMantle)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Tutorial_HowToSprint)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Tutorial_HowToWalk)
